plugins {
    id 'com.vanniktech.maven.publish' version '0.37.0' apply false
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'com.vanniktech.maven.publish'

    group = 'io.github.cosmicsilence'

    java {
        sourceCompatibility = JavaVersion.toVersion('25')
        targetCompatibility = JavaVersion.toVersion('25')
    }

    repositories {
        mavenCentral()
    }

    jar {
        manifest {
            attributes(
                'Implementation-Title': project.name,
                'Implementation-Version': project.version
            )
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(Javadoc).configureEach {
        options.encoding = 'UTF-8'
        options.addStringOption('Xdoclint:all,-missing', '-quiet')
    }

    mavenPublishing {
        publishToMavenCentral(false)
        signAllPublications()

        pom {
            name = project.name
            description = provider { project.description }
            url = 'https://github.com/cosmicsilence/bufferfly'
            inceptionYear = '2026'

            licenses {
                license {
                    name = 'The Apache License, Version 2.0'
                    url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                    distribution = 'repo'
                }
            }

            developers {
                developer {
                    id = 'thiagoampj'
                    name = 'Thiago Moraes'
                    url = 'https://github.com/thiagoampj'
                }
            }

            scm {
                url = 'https://github.com/cosmicsilence/bufferfly'
                connection = 'scm:git:https://github.com/cosmicsilence/bufferfly.git'
                developerConnection = 'scm:git:ssh://git@github.com/cosmicsilence/bufferfly.git'
            }
        }
    }
}
